### PR TITLE
Update cacert to Mozilla 6-24-2020

### PR DESCRIPTION
**Pull request by dlanderson**

### CODE REVIEW

**Comment by dlanderson** [comment]
Closes #346

**Comment by davidmccoy** [comment]
@dlanderson thanks for doing this! any chance this will be merged soon? (i'm the user that reported the original issue 😬 )

**Comment by davidmccoy** [comment]
just reporting back—i pointed my application to this branch and overrode the `SCOUT_SSL_CERT_FILE` environment variable with my proxy's certificate and Scout is now receiving traffic. thank you!

**Comment by dlanderson** [comment]
Closing - we're using https://github.com/scoutapp/scout_apm_ruby/pull/352 instead. Same functionality, but no updated pem file.

**Pull request closed without merging**
