### PR TITLE
ActiveRecord quick fix

### PR DESCRIPTION
**Pull request by ioquatix**
This PR implement a quick fix and regression tests to sort out https://github.com/scoutapp/scout_apm_ruby/issues/217

I've updated the travis test matrix in order to expand our ability to test combinations of different gems using the `gems/*.gemfile` approach which I've used in the past, and implemented a very basic test case for ActiveRecord.

Finally, I discussed the best way to fix this with @cschneid and we decided that a quick fix was preferable, and the mid-term solution is to deprecate Ruby < 2.1 going forward, but that requires a bit more effort. So, this PR is good to be merged IMHO, and paves the way for 3.x.

See also https://github.com/scoutapp/scout_apm_ruby/pull/270

### CODE REVIEW

**Comment by ioquatix** [comment]
@itsderek23 can you review this?

**Comment by ioquatix** [comment]
@cschneid should we merge this?

**Comment by itsderek23** [comment]
Thanks for the ping @ioquatix ... I'm not too familar with this one.

I believe @cschneid is heads-down on our PHP agent and is pretty stretched for time right now ... I'll take a pass late next week.

**Comment by dlanderson** [comment]
Sorry about that @ioquatix - I’ll review Monday. Thanks for the quick turnaround!

**Comment by ioquatix** [comment]
I am going to merge this in the next day or two.

**Comment by ioquatix** [comment]
Thanks for merging this!

**Pull request merged**
