### PR TITLE
AutoInstruments - Automatically break down uninstrumented time

### PR DESCRIPTION
**Pull request by dlanderson**
AutoInstruments breaks down uninstrumented Controller time automatically, by parsing the AST tree of your own application code when it boots.

Early adopters should try out the AutoInstruments Beta in staging and development environments. 

**You can try out this Beta by [following these steps](https://docs.scoutapm.com/#autoinstruments).**

If you have any questions please reach out to support@scoutapp.com!

### CODE REVIEW

**Comment by jsierles** [comment]
Note that this branch currently requires disabling bootsnap.

**Comment by ioquatix** [comment]
What was wrong with the Rails module usage? Just curious.

**Comment by dlanderson** [comment]
> What was wrong with the Rails module usage? Just curious.

@jsierles and others hit an exception with newer Rail versions: `uninitialized constant ActiveSupport::Executor (NameError)`. It seemed to be caused by a Rails loader while Rails was in the process of being loaded itself. Avoiding it entirely seems the safest bet.

**Comment by ioquatix** [comment]
I have rebased on master.

**Comment by jonekdahl** [comment]
Is there already a config switch to enable/disable AutoInstruments? Otherwise, I'd like to request one.

**Comment by jonekdahl** [comment]
@ioquatix Yes, that seems to work, thanks. Although I think people will expect a regular Scout config, like http://help.apm.scoutapp.com/#profile.

**Comment by jsierles** [comment]
Has this work been abandoned? We tried this on our production environment, and found that many traces showed even less information the previous traces, so we reverted.

**Comment by ioquatix** [comment]
@jsierles do you mind giving me a bit more feedback?

We could try rebasing on master. In theory it shouldn't be less than before, and ideally more.

**Comment by jeremy** [comment]
```ruby
# Added AFTER `File.expand_path('../../Gemfile', __FILE__)`
# But BEFORE `require 'bundler/setup'`
require 'scout_apm/auto_instrument'
```

How can this work, considering `scout_apm` is itself bundled?

**Comment by ioquatix** [comment]
@Jeremy I believe this goes into your own config `config/boot.rb` so `File.expand_path('../../Gemfile', __FILE__)` resolves to `Gemfile` in your app - is that what you were questioning?

**Comment by jeremy** [comment]
@ioquatix Bundler setup is what sets up the load path so bundled gems can be required… so how can we require scout_apm BEFORE Bundler setup, unless you require installation as a system gem? (Pardon if I'm missing something here!)

**Comment by ioquatix** [comment]
@itsderek23 if you want to do a rebase on master I am also happy with that.

**Comment by itsderek23** [comment]
@ioquatix - thanks! Not ready quite yet - we're getting our ducks in a row for this.

**Comment by ioquatix** [comment]
I would suggest hard reset to 4e8a98a and rebase on master, then squash merge. There are lots of WIP commits. Let me know if you want me to squash it down.

**Comment by ioquatix** [comment]
I am making the requested change to the class name tracking and squashing this branch in preparation for merging.

**Comment by itsderek23** [comment]
@ioquatix - naming update is looking good. Makes it far more intuitive to go to the source in the UI. Thanks!

image

**Comment by ioquatix** [comment]
That's awesome!

**Comment by itsderek23** [comment]
@ioquatix - what do you recommend we call the code pieces we are instrumenting? It's more fine-grained than lines. 

For example:

`if A || B` looks to be broken up into instrumenting `A` and `B` separately.

**Comment by ioquatix** [comment]
Expressions?

Method invocations?

**Comment by itsderek23** [comment]
@dlanderson - The instructions state to also add `parser` to your Gemfile. 

This is listed as dev dependency:

```
s.add_development_dependency "parser"
```

...should we just use `#add_development_dependency` so no other dependencies are manually required?

**Comment by dlanderson** [comment]
> ...should we just use `#add_development_dependency` so no other dependencies are manually required?

Do you mean `#add_runtime_dependency`? I'm ok with that.

**Comment by dlanderson** [comment]
I would also like to remove the `boot.rb` step. Perhaps we put ourselves into the Rails boot process as a Railtie? @ioquatix Would you be able to look into that?

**Comment by itsderek23** [comment]
> Do you mean #add_runtime_dependency? I'm ok with that.

Ah yes - I'll do that. Thanks!

**Comment by dlanderson** [comment]
@ioquatix  I also wonder if we inject ourselves via a Railtie if this will allow us to play nicely with [Bootsnap](https://github.com/Shopify/bootsnap). Currently when we load via `boot.rb` only one of either Scout or Bootsnap can work (whichever is listed in `boot.rb` last).

**Comment by ioquatix** [comment]
I can investigate it.

**Comment by ioquatix** [comment]
@itsderek23 do you mind avoiding doing merge commits into this branch, the way you are doing it duplicates the entire history.

**Comment by ioquatix** [comment]
https://github.com/scoutapp/scout_apm_ruby/blob/b8f88c20d41c17a9193264afa717f2a2ca9a3332/lib/scout_apm.rb#L185-L211

This is what we have already.

I assume it's not sufficient since we still advise to put it in `boot.rb`.

**Comment by ioquatix** [comment]
What we could do is add `require 'scout_apm/auto_instrument'` within that railtie.

**Comment by itsderek23** [comment]
Sorry for the merge commits! I'll avoid.

**Comment by ioquatix** [comment]
That’s awesome!

**Comment by jonekdahl** [comment]
Is there any chance of this getting merged and included in a release, keeping it disabled by default? It would allow us to use the same version of the gem in all environments and enable the feature in selected test environments. Using a different version/branch of a gem in a specific environment in a continuous delivery pipeline is a pain.

**Comment by itsderek23** [comment]
@jonekdahl,

> Is there any chance of this getting merged and included in a release, keeping it disabled by default? 

This is our plan. We want to get some more installs of the `auto_instruments` branch before merging into master, but we don't anticipate this lasting more than a month.

**Comment by ioquatix** [comment]
@dlanderson I've added some initial checks for local assignments. I've added some tests, but I still need to see the code which caused https://github.com/scoutapp/scout_apm_ruby/issues/281 to fail.

**Comment by ioquatix** [comment]
Sorry, hit wrong button.

**Comment by itsderek23** [comment]
@jonekdahl - We've merged this into master (version 2.6.0). 

To enable autoinstruments, set the `auto_instruments` config option to `true`. 

[Details in our docs](https://docs.scoutapm.com/#enabling-autoinstruments).

**Comment by mathieujobin** [comment]
@itsderek23 docs still suggest we should update our `config/boot.rb`
from this PR conversation, it sounds like this is outdated

**Comment by dlanderson** [comment]
@mathieujobin Apologies - docs need updating. We have released AutoInstruments in 2.6.0. To enable, just set `auto_instruments: true` in `scout_apm.yml`, or `SCOUT_AUTO_INSTRUMENTS=true` in Env vars if Heroku.

**Comment by itsderek23** [comment]
@mathieujobin - Apologies. I forgot to publish the changes. 

Docs are [updated](https://docs.scoutapm.com/#autoinstruments).

**Comment by mathieujobin** [comment]
getting a syntax error on deploy

```
I, [2019-09-19T23:26:12.525601 #20423]  INFO -- : Refreshing Gem list
warning: parser/current is loading parser/ruby24, which recognizes
warning: 2.4.7-compliant syntax, but you are running 2.4.6.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/home/rails/.rvm/gems/ruby-2.4.6@payroll_hero/gems/scout_apm-2.6.0/lib/scout_apm/auto_instrument/instruction_sequence.rb:11:in `compile': members_controller.rb:32: syntax error, unexpected tOP_ASGN, expecting keyword_end (SyntaxError)
roy'"]){department.members} -= [::ScoutApm::AutoInstrument("
                              ^
        from /home/rails/.rvm/gems/ruby-2.4.6@payroll_hero/gems/scout_apm-2.6.0/lib/scout_apm/auto_instrument/instruction_sequence.rb:11:in `load_iseq'
        from /home/rails/.rvm/gems/ruby-2.4.6@payroll_hero/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
```

**Comment by ioquatix** [comment]
I can take a look

**Comment by mathieujobin** [comment]
this is in our code

```
    def destroy
      department.members -= [current_account.employees.find_by!(account_specific_id: params.require(:id))]

      respond_to do |format|
        format.html {}

        format.json do
          render json: members_as_json
        end
      end
    end
```

**Pull request merged**
