### PR TITLE
Fix bad Sidekiq::Processor patch causing failures on 6.5.0

### PR DESCRIPTION
**Pull request by bf4**
Closes https://github.com/scoutapp/scout_apm_ruby/issues/449

Note: this code path does not appear to be tested

### CODE REVIEW

**Review by PikachuEXE — APPROVED** [review]

**Comment by bf4** [comment]
This repo maintained? Lol, we pay for scout

**Comment by PikachuEXE** [comment]
Well I will wait for a week before thinking this repo might be unmaintained...

**Comment by dlanderson** [comment]
Hello! Yes, it is. We maintain backwards compatibility with older versions of sidekiq and I do not know when the `on(:startup)` hook was introduced but we need to confirm that this change will be handled gracefully for older versions. We very much appreciate the PR contribution and will get it reviewed/merged as soon as we can.

**Comment by mperham** [comment]
3.0.0 eight years ago.

**Review by dlanderson — APPROVED** [review]

**Comment by bf4** [comment]
I should mention that I tested this executes the ScoutApm::Agent.instance.start code in my application running on this PR

**Comment by dlanderson** [comment]
Thanks @bf4 - looks good to me! I’ll see about adding a test and get it merged tomorrow.

And thanks for letting me know about the on startup hook history @mperham !

**Comment by bf4** [comment]
@dlanderson Thanks for following up with the test https://github.com/scoutapp/scout_apm_ruby/pull/451

**Comment by rkallensee** [comment]
@dlanderson Are there any plans to do a gem release with the fix? Would be great to be able to use Sidekiq 6.5.

**Comment by bf4** [comment]
I've been running on main without issues as well

**Comment by dlanderson** [comment]
Thanks again for your patience all - 5.2.0 is released

**Pull request merged**
