### PR TITLE
add background job support for que v0.14.3

### PR DESCRIPTION
**Pull request by nearapogee**
The commit adds support for Que v0.14.3. Que 1.0.0 is going to have significant changes especially relating to ActiveJob.

I have tested it locally and it appears to be working in my account. If you like it and accept it. I can deploy it on a few applications.

Please let me know if I missed anything!

### CODE REVIEW

**Comment by nearapogee** [comment]
Didn't think about 1.8 support, etc. Oops.

**Comment by nearapogee** [comment]
This is failing on `$ gem update --system`. Is that something I need to fix? Would like to get back on the normal release schedule!

Let me know if I can help!

**Comment by cschneid** [comment]
@nearapogee what error with `gem update --system` are you seeing?

**Comment by nearapogee** [comment]
https://travis-ci.org/scoutapp/scout_apm_ruby/jobs/471048360

Just on Travis. I am just hoping to get this merged in and on a future release. I have been using this branch for months since I signed up for Scout App.

Just trying to clear up any holdup! Thanks for Scout!

**Comment by dlanderson** [comment]
@ioquatix Might be able to review and help get this merged!

**Comment by ioquatix** [comment]
Sure, can look at it today.

**Comment by ioquatix** [comment]
I've merged into a local branch and will review.

**Pull request merged**
