### PR TITLE
Ignores autoinstrument layers under 5ms in total call time and naming tweaks

### PR DESCRIPTION
**Pull request by itsderek23**
Autoinstrument layers are more likely to have fast execution times that are below a reasonable threshold for optimization. This discards autoinstrument layers that are under 5ms in total_call_time.

### CODE REVIEW

**Comment by itsderek23** [comment]
This also includes some changes to we create layers:

* Using the code expression as the metric name
* Setting a partial backtrace, which we're able to collect from the source file path.

How it looks in the UI:

image

**Comment by itsderek23** [comment]
Tests are broken because of the naming layer naming change. Investigating.

**Comment by ioquatix** [comment]
Do you want me to merge this into auto_instruments branch?

**Comment by itsderek23** [comment]
Yes

**Comment by ioquatix** [comment]
Okay it's merged. Let's work on `auto_instruments` branch now if it makes sense.

**Comment by ioquatix** [comment]
It's merged.

**Pull request closed without merging**
